### PR TITLE
Update MUI logo

### PR DESCRIPTION
**Pull request by oliviertassinari**
https://bestofjs.org/projects/mui

Before

Screenshot 2022-02-06 at 17 39 46

After

Screenshot 2022-02-06 at 17 40 00

A few more thoughts:

- It could be simpler to use the avatar in https://github.com/mui/
- The npm package is outdated: `@mui/material` is the latest one with v5.
- The GitHub URL is wrong: https://github.com/mui/material-ui
- For the name of the project. MUI is our company name, but maybe keeping Material UI here would be clearer.

cc @danilo-leal for context.

### CODE REVIEW

**Comment by michaelrambeau** [comment]
Hello Olivier @oliviertassinari 
Thank you very much, I'm going to merge and release.
Sorry for the wrong logo, I spend a lot of time collecting and editing SVG files for the most important projects (projects called "Featured Projects" in the top page, for other projects I just use the GitHub avatar of the owner) but sometimes SVG logos I use are out of date.
This is why this project is open-source 😅 

I prefer to use a SVG file when it's possible because they are lighter than than the images files served by GitHub, they render better no matter the resolution and I can make adjustments to handle light and dark modes.

About the GitHub URL, I think it's correct right now, the reason is because data is updated from GitHub autiomatically every 24 hour and I suppose you changed something on Sunday?

image

I will fix the NPM package name.


I will ping you to check everything very soon, stay tuned!

**Comment by michaelrambeau** [comment]
An other remark about the project name: it used to be called `Material UI`but I changed to "MUI" in December when I noticed the description in the official home page was:

> MUI provides a robust, customizable, and accessible library of foundational and advanced components, enabling you to build your own design system and develop React applications fast

Note: it's also called MUI in the _Rising Stars_ since the data is the same.
https://risingstars.js.org/2021/en

The project's name is used to compute the project slug (`/projects/:slug`): https://bestofjs.org/projects/mui

**Comment by oliviertassinari** [comment]
> I suppose you changed something on Sunday?

Correct

> it used to be called Material UIbut I changed to "MUI" in December when I noticed the description in the official home page was:

Yeah, it's fair, we have been oscillating a bit on the exact scope of the different names. It's also a bit blurry to what people are actually staring. https://mui.com/blog/material-ui-is-now-mui/ is our official stance on the matter. For the repository, many people have been handling https://github.com/mui/material-ui as === the primary project of the organization MUI, which is still true. We are progressively trying to complement the offering, breaking this strong ===.

**Comment by michaelrambeau** [comment]
OK Olivier @oliviertassinari the changes have been published:

- Logo up-to-date (to be honest I miss the previous one that had more colors 😅 )
- NPM package name fixed
 
It must be late in France but could you check again https://bestofjs.org/projects/mui?

Screenshot:

image

Thank you in advance!

**Comment by michaelrambeau** [comment]
## Bonus

The logo is also up-to-date in the _Rising Stars_: https://risingstars.js.org/

image

**Comment by oliviertassinari** [comment]
> (to be honest I miss the previous one that had more colors 😅)

Haha, well, we haven't given our last shot at it yet. We might come up with something better for v6 in 2023. A first exploration https://github.com/mui/material-ui/pull/30497

**Comment by michaelrambeau** [comment]
Thank you Olivier for the logo preview and for having checked the changes!

And if you have any idea to improve _Best of JS_, your feedback would be very valuable, of course.

**Pull request merged**
