### PR TITLE
Upgrade to vite 3

### PR DESCRIPTION
**Pull request by nvh95**
## Goal
- Upgrade to Vite 3. Vite team just announce Vite 3.0.0 (https://vitejs.dev/blog/announcing-vite3)

## How to test
- We need to test on Vercel preview page **manually** 
- We need to have some e2e tests here. Since integration tests only test the code at JSDOM level. It cannot test if our build process.

## Caveats
- `vite-plugin-checker@0.4.6` require `vite@2`. Version 0.4.9 (https://github.com/fi3ework/vite-plugin-checker/commit/cd1f06f) resolves it.

## Pending
- [x] Some issues with `npm ci` in GitHub Actions

### CODE REVIEW

**Comment by nvh95** [comment]
@michaelrambeau 
FYI Our integration tests with Jest cannot cover updates like this. So in the future, we need some end-to-end tests to cover some golden flows like #147

**Comment by nvh95** [comment]
@michaelrambeau It's actually a bug and being tracked here https://github.com/vitejs/vite/issues/9174

**Comment by nvh95** [comment]
@michaelrambeau The font issue has been fixed in vite `3.0.4`. Can you help to check it again? Thanks

**Review by michaelrambeau — APPROVED** [review]
👍 Fonts are now displayed correctly. 

Thank you very much Hung for your investigation, contribution to Vite project and upgrade of _Best of JS_, you are the best 😄 !

**Pull request merged**
