### PR TITLE
Enhance HTTP security headers

### PR DESCRIPTION
**Pull request by chuongtrh**
## Goal
Enhance security headers in file vercel.json

## How to test
Tracking security header at [here](https://securityheaders.com/?q=https%3A%2F%2Fbestofjs.org&followRedirects=on)
## Screenshots
screencapture-securityheaders-2022-07-18-15_49_58

### CODE REVIEW

**Review by michaelrambeau — CHANGES_REQUESTED** [review]
Thank you @chuongtrh for the investigation.

Unfortunately it's not possible to deploy those changes as the Vercel setup cannot include both `routes` and `headers`.

> If `rewrites`, `redirects`, `headers`, `cleanUrls` or `trailingSlash` are used, then `routes` cannot be present.

https://vercel.link/mix-routing-props

**Comment by chuongtrh** [comment]
@michaelrambeau Could you help to review it again?

**Comment by michaelrambeau** [comment]
Thank you the changes @chuongtrh 
I wonder what is the difference between the 2 regular expressions:

- `/[^.]+` the one for the routing in the SPA (we want to redirect requests for any page to index.html) 
- `/(.*?)` the one you added about headers?
 
Could everything be combined?
Or should the rule about the headers apply to only `index.html` route?

Note: according to Vercel docs, the `routes` property is not recommended https://vercel.com/docs/project-configuration#legacy/routes but I don't know if there an other way to achieve the routing in the SPA.

**Comment by chuongtrh** [comment]
Thank you @michaelrambeau 

- Using [rewrites](https://vercel.com/docs/project-configuration#project-configuration/rewrites) to achieve routing in SPA
- Remove **routes**, it not recommended by vercel

**Review by michaelrambeau — APPROVED** [review]
Thank you again for the changes @chuongtrh 👍 

I'm merging into the `develop` branch, it will be deployed to production later, after a few tests.

**Comment by michaelrambeau** [comment]
The `develop` branch has been deployed, you can check the result here: https://bestofjs-git-develop-bestofjs.vercel.app/

**Pull request merged**
