### PR TITLE
Add dynamic page titles using react-helmet

### PR DESCRIPTION
**Pull request by BBlackwo**
Add dynamic page titles using react-helmet as discussed in #106.

- Created `<Title>` that wraps the `<PageTitle>`
- In places where `<PageTitle>` is not used, use React Helmet directly

### CODE REVIEW

**Comment by michaelrambeau** [comment]
Thank you Benjamin for your hard work, it works 👍 !

I checked online and I was happy to be able to see the title page, which is convenient when when you open a project's page for example.

image

Not very important but maybe we could merge the constants provided by this "container" https://github.com/bestofjs/bestofjs-webui/blob/develop/src/containers/static-content-container.tsx with the ones you created in the new file `constants/contants.ts`, especially because both mention the app title `Best of JS`.

But don't worry, you are not supposed to know the whole structure of the app (that has 6 years of history 😄!).

What I could do to decouple the development process and the release to production is to setup `develop` as the default branch (the one use to merge PR), while `master` is the production branch (that triggers the deployments to production).

This why I can merge your branch and later update the CHANGELOG and the version number that shows up in the "App Update" notification (i don't know if you have ever noticed this "toast").

**Comment by michaelrambeau** [comment]
Thank you again for the improvements @BBlackwo Benjamin, I'm merging and I'm going to do a bit of refactoring because of the "technical debt".

**Comment by BBlackwo** [comment]
Sounds good to merge the constants :+1: 

Good to know about the `develop` branch. Will use that next time.

I haven't seen the "App Update" notification :thinking: Does that just pop up when you load the page and it has updates?

**Comment by michaelrambeau** [comment]
Hello @BBlackwo 

No worries, I have already setup the `develop` branch as the default one and I have merged everything (check the other PR #108 if you are interested)

The "toast" shows up when there is a release, it includes the next version number (if the user accepts and reloads the window).

image

**Pull request merged**
