### PR TITLE
Dark mode feature

### PR DESCRIPTION
**Pull request by michaelrambeau**
## Goal

Provide a dark mode because all good applications for developers provide a dark mode.

it was requested by my friend @L1lith on Discord too!

image

This PR introduces [ChakraUI](https://chakra-ui.com/d) as the UI framework to build our React components.

## Screenshots (first iteration)

image

### CODE REVIEW

**Comment by michaelrambeau** [comment]
## Iteration 2

Customize the search box to handle the dark mode, using as much as possible ChakraUI components rather than the default components provided by `react-select`.

About how to customize `react-select` theme: https://github.com/JedWatson/react-select/issues/3692#issuecomment-523425096

image

**Comment by michaelrambeau** [comment]
## Bundle size

The main issue is the impact on the bundle size.
It seems that adding ChakraUI and its dependency `framer-motion` adds `82 kB` (gzipped) to the main bundle file 😱 

image

**Comment by michaelrambeau** [comment]
## Bundle size (following the previous comment)

After having included more components from ChakraUI, the main bundle has increased and reached the size of `197.77 KB` according to the build command.

Checking the preview URL in the browser https://bestofjs-git-try-chakra-ui-bestofjs.vercel.app/, the size of the file `2.757769c1.chunk.js` is`205 kB`.

In production, it's currently `111 kB` (see the [latest release](https://github.com/bestofjs/bestofjs-webui/releases/tag/0.32.1))... it's a big increase (+94 kB) that has an impact on performance! 🙀 

According to `source-map-explorer`, here are the sizes (gzipped) of the packages introduced by ChakraUI:

- ChakraUI: 50 kB
- Framer Motion: 22 kB
- Popper: 5 kB
- Tinycolor: 4 kB
- Popmotion: 3 kB

image

**Comment by davidcetinkaya** [comment]
Hi @michaelrambeau!

Please forgive me if I'm missing something obvious here, I haven't used Chakra UI myself, but did you introduce Chakra UI to achieve dark mode?

Best,
David

**Comment by michaelrambeau** [comment]
The dark mode feature was only one of the reasons that made me try ChakraUI in _Best of JS_. I'm very familiar with this framework and I love the approach of the "style props", so I wanted to make _Best of JS_ components more robust and take advantage of the great developer experience provided by ChakraUI.

About the "style props" concept, I think the idea comes from [Styled System](https://styled-system.com/) project but ChakraUI has it own "styled system".

Instead of using a framework like ChakraUI, we could build our own components on top of [XStyled](https://styled-system.com/).

> With xstyled, CSS is declarative. It fits with React philosophy, writing CSS is as easy as writing props.

**Comment by michaelrambeau** [comment]
## Time to merge!

It's time to release the Dark mode after a lot of iterations and attempts to decrease the bundle size.

I tried a lot of things to make the bundle smaller, it was a real dilemma that has been tormenting me for days: relying on a framework or doing everything by myself.

Finally I chose to use ChakraUI but without some heavy components that use animations: so I created the Menu component using [Headless UI](https://headlessui.dev/) instead of using ChakraUI menu component.

Among the changes the base font size is now `16px` (instead of `14px`).

#### Screenshots

image


image

**Comment by BBlackwo** [comment]
Michael @michaelrambeau, I'm curious, what was the final bundle size with your library changes?

**Comment by michaelrambeau** [comment]
Thank you for your interest in the bundle size Benjamin, I feel less lonely now 😄 
So the current size of the main bundle is `163 kB`, on this branch.

On production, it's `114 kB`.

**Comment by BBlackwo** [comment]
Ok, that's not too bad then. Nice work bringing the size down!

**Pull request merged**
