### PR TITLE
Increase Developer Experience by replacing Create React App with Vite

### PR DESCRIPTION
**Pull request by nvh95**
## Motivation
- Decrease the start and build time significantly. Start under 500ms, build under 5 seconds.

## Benchmark

|      | npm start | npm build |
|------|-----------|-----------|
| CRA  | 8.2s      | 17s       |
| Vite | 0.4s      | 5.1s      |

Vite is **20 times faster** when starting a dev server.
Vite is **3.4 times faster** when building app.
(Benchmarked on Macbook Air M1 2020)

## Changes
- [x] Packages changes
  - [x] Remove `react-scripts`
  - [x] remove `react-router`, only need react-router-dom
  - [x] Remove `tinytime`. Since it has some issue with Vite (`jsnext:main` point to `.js` code with flow syntax makes Vite confused). Replaced by `date-fns` (6kb gzipped)
  - [x] Add `fs-extra`. Currently, it’s not in the `package.json`, but the dependency of `react-scripts`
  - [x] Update `typescript` to newest version (`4.6.3`)
- [x] Fix some typescript issues
- [x] Remove unused CRA service worker code
- [x] Fix a typo in routes (`src/pages/routes.tsx`):
```diff
-<Route from={`/tags`} component={TagsPage} />
+<Route path={`/tags`} component={TagsPage} />
```
- [ ] Variable environments
  - [x] Change prefix: `REACT_APP` => `VITE_APP`. 
  - [ ] Need to update in Vercel settings as well (if have any) @michaelrambeau to do and mark as done
  - [ ]  Remeber to update `REACT_APP_ENV: production` to `VITE_APP_ENV: production` in Vercel as well @michaelrambeau to do and mark as done
- [x] Support [ejs](https://ejs.co/) in `index.html` to inject `cloudflareinsights` script.
- [x] Support light mode and dark mode logo (`bestofjs-logo.svg`) (#E65100 vs ##F6AD55)
- [x] Integrate Jest with Rust-based compiler SWC
- [x] Add GitHub Actions to run tests on Push and PR

## How to test
- Just run:
```bash
npm i
npm run start
```

## Screenshots
dev sever ready less than 0.5 seconds

### CODE REVIEW

**Comment by michaelrambeau** [comment]
@nvh95 Thank you again for the time you spend on _Best of JS_, I appreciate your help.

I'm aware that the code is not very clean, types have been added but not everywhere, so I'm sorry if you had trouble with types, I should have cleaned before.

Some context about _Create React App_: the reason I chose it is their concept of `0 configuration`, no upgrade nightmare with dependencies like Babel, Webpack, ESLint, SVG loading, fast refresh and everything, it just works without having to think about dependencies. 

Also I like their TypeScript integration: they always upgrade when it's stable and I like the fact the compiler checks types in development mode after every change. (I know some people prefer to have the type checking only when they build for production).

That being said, I know Vite is a great solution, so I'm open to any solution to improve the "DX", so I'm very curious about your result and I will check your branch.

One more thing: I was working on a new architecture using Next.js framework to enjoy some features like SSR but this task has been delayed, it's still a prototype.

**Comment by nvh95** [comment]
@michaelrambeau 
I'm the one who needs to say thank you. I learn a lot from https://bestofjs.org/ for the last year.
> I'm aware that the code is not very clean, types have been added but not everywhere, so I'm sorry if you had trouble with types, I should have cleaned before.

Your code is super clean already. I also learned a lot. I can see in some places we can improve the types and I will try to add it to this PR as well.

> Some context about Create React App

Yeah. We all used CRA. But [it's not in active development anymore](https://github.com/facebook/create-react-app/issues/11180) (maintenance mode with very slow progress). I adopted Vite as an alternative for CRA about 8 months ago and I'm very happy with that. It's not like zero-configuration but it's not very complicated. And the most important thing is the speed gain when develop and build an app (Vite leverages native ESM support in modern browsers, eliminates the concept of bundling during develop, it also use `esbuild` underhood which is super fast).

> I'm very curious about your result and I will check your branch.

I will update the PR description with the changes I made and some things I need your opinions on. I will also add a benchmark table as well.

> I was working on a new architecture using Next.js framework to enjoy some features like SSR

That would fix #114. I also want to do that but it's not an easy task. So I chose to migrate CRA to Vite first to improve the DX first. And leave the SSR task for future development. We can consider Next.js (the most mature option now), or Remix (potential candidate), [Vite SSR](https://vitejs.dev/guide/ssr.html) (which I'm looking forward, [version 3 is coming](https://github.com/vitejs/vite/releases/tag/v3.0.0-alpha.1)).

I would love to help with the work on Next.js. I haven't had a chance to work with Next.js on production, so it might be a good one for me. Let me know if you need any help.


I used to bootstrap a new app using Vite. But I haven't had a chance to migrate a CRA app to Vite so `bestofjs-webui` is a great opportunity for me to practice my skills. I learned a lot during the migration. I will mark this PR as `Ready to Review` and mention you very soon.

Thank you very much.

**Comment by michaelrambeau** [comment]
Thank you for your comments @nvh95 !
About the migration to Vite, you convinced me 🤝 😄 , I will check your branch as soon as I fixed the "Timeline" page, adding what is missing.

About the future...

The current app is limited by the current architecture (SPA approach, we load a huge JSON file and all search queries happen in the browser) I'd like to handle more projects, having a server to query.

Next.js has great SSG features (it would be great to generate a new home page on the server everyday when data is updated, for example).

Remix approach looks very interesting too and maybe more appropriate to Best of JS use case (we have a lot of search requests that can combine query and sort filters, it's impossible to generate statically all the combinations, so the "dynamic" approach of Remix could be great).

We can talk if you are interested, we are on Discord or I can invite you to our Slack team, as you want.
Both spaces are very quiet!

**Comment by nvh95** [comment]
@michaelrambeau I would love to join. Can you send me slack and discord invitation links to my Direct Message on [my twitter](https://twitter.com/hung_dev)? Thanks.

> we load a huge JSON file and all search queries happen in the browser
I see. I think I need to get involved more to fully understand the current limitation. Some keywords pop up in my head
- Algolia: very famous, free for open-source, technical sites
- Flexsearch: full text search solution used by [Nextra](https://nextra.vercel.app/) (an example: https://swr.vercel.app/)

**Comment by nvh95** [comment]
@michaelrambeau I updated the PR description. Please take a look

**Review by michaelrambeau — APPROVED** [review]
@nvh95 Thank you very much Hung for this amazing work!

To sum up the changes:

- The app starts fast
- The app builds fast
- The tests are fast
- You cleaned all files to remove the old `js` files
- As a bonus, we have tests that run in the cloud with test coverage


And we still have the instant feedback from the compiler if there are TypeScript errors, like in the previous set up.

This is amazing! 🤩

**Comment by michaelrambeau** [comment]
## About the testing setup

The testing setup approach with SWC is described by a post from @nvh95 himself:

https://hung.dev/jest-vite

**Comment by L1lith** [comment]
@michaelrambeau It might also be worth checking out in the future is [Astro](https://astro.build). I haven't used vite much before directly but it's built on top of vite and has a lot of nifty features (like querying data at build time to be used for SSG)

**Pull request merged**
